---
- name: Sync services to server
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../services/"
    dest: /opt/services/
    delete: yes
    recursive: yes

- name: Find compose projects
  ansible.builtin.find:
    paths: /opt/services
    patterns: docker-compose.yml
    file_type: file
    recurse: yes
  register: compose_files

- name: Start services
  community.docker.docker_compose_v2:
    project_src: "{{ item.path | dirname }}"
    state: present
    remove_orphans: true
  loop: "{{ compose_files.files | sort(attribute='path') }}"
  loop_control:
    label: "{{ item.path | dirname | basename }}"
