name: glance

services:
  glance:
    image: glanceapp/glance:latest
    restart: unless-stopped
    environment:
      TZ: "${TZ:-Etc/UTC}"
    networks:
      - proxy
    volumes:
      - ./glance.yml:/app/config/glance.yml:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
    name: proxy
