[tools]
ansible-core = "latest"
helm = "latest"
helmfile = "latest"
hugo = "latest"
kubectl = "latest"
packer = "latest"
talosctl = "latest"
terraform = "latest"

[env]
_.file = "core/ansible/.env"

[tasks.bootstrap]
run = "cd bootstrap && terraform init && terraform apply -auto-approve"
description = "Bootstrap S3 backend for terraform state"

[tasks.create-proxmox-usb]
run = "./scripts/create-proxmox-usb.sh"

[tasks.install-tailscale]
run = "cd core/ansible && ansible-playbook site.yml --tags tailscale"

[tasks.configure-proxmox]
run = "cd core/ansible && ansible-playbook site.yml --skip-tags tailscale"

[tasks.configure-tailnet-for-k8s]
run = "cd distros/talos/terraform && terraform init && terraform apply -target=module.tailscale -auto-approve"

[tasks.deploy-proxmox-vms]
run = "cd distros/talos/terraform && terraform apply -target=module.proxmox -auto-approve"

[tasks.bootstrap-talos-linux-nodes]
run = "cd distros/talos/terraform && terraform apply -target=module.talos -auto-approve"

[tasks.deploy-k8s-services]
run = "cd distros/talos/manifests && helmfile apply"

[tasks.docs]
run = "cd docs && hugo server --buildDrafts"
description = "Serve and open docs site"
