---
go_install_path: "/opt/go"
go_bin_path: "/opt/go/bin"

caddy_user: "caddy"
caddy_group: "caddy"
caddy_home: "/var/lib/caddy"
caddy_binary_path: "/usr/bin/caddy"
caddy_config_dir: "/etc/caddy"
caddy_systemd_service: "/etc/systemd/system/caddy.service"

caddy_plugins:
  - "github.com/caddy-dns/cloudflare"

reverse_proxy_domain: "proxmox.seagram.cloud"
reverse_proxy_backend: "https://localhost:8006"
reverse_proxy_tls_insecure: true

cloudflare_api_token_secret_name: "/homelab/cloudflare_api_token"

caddy_limit_nofile: 1048576
caddy_limit_nproc: 1048576
caddy_timeout_stop_sec: "5s"

caddy_dependencies:
  - debian-keyring
  - debian-archive-keyring
  - apt-transport-https
  - curl
  - golang-go
