---
all:
  hosts:
    ubuntu:
      ansible_host: "{{ lookup('env', 'TARGET_IP') }}"
      ansible_user: ubuntu
    ubuntu-tailscale:
      ansible_host: "{{ lookup('env', 'TAILSCALE_MAGIC_DNS_NAME') }}"
      ansible_user: ubuntu
