---
- name: Configure Debian Host
  hosts: debian
  become: true
  tasks:
    - import_tasks: tasks/install_tailscale.yml
      tags: tailscale
    - import_tasks: tasks/apt_update.yml
      tags: apt
    - import_tasks: tasks/harden_ssh.yml
      tags: ssh
    - import_tasks: tasks/disable_poweroff.yml
      tags: poweroff
