---
- name: Configure Proxmox
  hosts: proxmox
  become: true
  vars:
    cpu_scaling_governor: powersave # performance | powersave | schedutil
  tasks:
    - import_tasks: tasks/configure_repos.yml
      tags: repos
    - import_tasks: tasks/set_cpu_scaling_governor.yml
      tags: governor
    - import_tasks: tasks/create_admin_user.yml
      tags: admin
    - import_tasks: tasks/install_tailscale.yml
      tags: tailscale
    - import_tasks: tasks/apt_update.yml
      tags: apt
    - import_tasks: tasks/harden_ssh.yml
      tags: ssh
    - import_tasks: tasks/install_nginx.yml
      tags: nginx
    - import_tasks: tasks/disable_poweroff.yml
      tags: poweroff
