services:
  homelab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ansible-cache:/workspace/ansible/.ansible
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - $HOME/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
    environment:
      # SSH Agent for Tailscale SSH
      - SSH_AUTH_SOCK=/ssh-agent
      # AWS
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # Ansible
      - ANSIBLE_CONFIG=/workspace/ansible/ansible.cfg
      - ANSIBLE_HOST_KEY_CHECKING=False
    env_file:
      - ../.env
    working_dir: /workspace
    network_mode: host
    stdin_open: true
    tty: true

volumes:
  ansible-cache:
