---
- name: Remove enterprise repository
  ansible.builtin.apt_repository:
    update_cache: false
    repo: deb https://enterprise.proxmox.com/debian/pve trixie pve-enterprise
    state: absent

- name: Remove enterprise pbs repository
  ansible.builtin.apt_repository:
    update_cache: false
    repo: deb https://enterprise.proxmox.com/debian/pbs trixie InRelease
    state: absent

- name: Add community repository
  ansible.builtin.apt_repository:
    update_cache: true
    repo: deb http://download.proxmox.com/debian/pve trixie pve-no-subscription
    state: present
