name: uptime-kuma

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    restart: unless-stopped
    environment:
      TZ: "${TZ:-Etc/UTC}"
    networks:
      - proxy
    volumes:
      - uptime_kuma_data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true
    name: proxy

volumes:
  uptime_kuma_data:
