---
- name: Configure Proxmox Host
  hosts: proxmox-ssh
  roles:
    - role: disable-power-off
      tags: [configure-proxmox]
    - role: update-apt
      tags: [configure-proxmox]
    - role: tailscale
      tags: [configure-proxmox]

- name: Install Reverse Proxy
  hosts: proxmox-tailscale
  roles:
    - role: reverse-proxy
      tags: [reverse-proxy]

- name: Configure k3s Nodes
  hosts: control-node-ssh,worker-node-1-ssh,worker-node-2-ssh
  become: true
  roles:
    - role: tailscale
      tags: [configure-k3s]
