server:
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: longhorn
  global:
    scrape_interval: 30s

alertmanager:
  persistence:
    enabled: true
    storageClass: longhorn

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
