---
- name: Update APT packages
  hosts: all
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
      register: apt_cache_update

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
        force_apt_get: yes
      become: true
      register: apt_upgrade_result

    - name: Check if Proxmox is installed
      ansible.builtin.stat:
        path: /usr/bin/pveupgrade
      register: pveupgrade_exists

    - name: Upgrade Proxmox VE packages
      ansible.builtin.command:
        cmd: pveupgrade
      become: true
      register: proxmox_upgrade_result
      when: pveupgrade_exists.stat.exists
      changed_when: "'No packages will be upgraded' not in proxmox_upgrade_result.stdout"

    - name: Display Proxmox upgrade status
      ansible.builtin.debug:
        msg: "{{ proxmox_upgrade_result.stdout_lines }}"
      when:
        - pveupgrade_exists.stat.exists
        - proxmox_upgrade_result is defined
