---
- name: Disable power off on lid close
  lineinfile:
    path: "{{ logind_conf_path }}"
    regexp: "^#?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    backup: yes
  loop: "{{ disable_poweroff_lid_keys }}"

- name: Restart systemd-logind
  systemd:
    name: systemd-logind
    state: restarted
    daemon_reload: yes
